project:
  type: website
  output-dir: docs

website:
  title: "Anand Hegde"
  site-url: https://anandshegde.github.io/
  favicon: images/A-logo.png

  navbar:
    logo: images/A-logo.png
    right:
      - href: index.qmd
        text: Home
      - href: education.qmd
        text: Education
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: files/CV_Anand_Hegde_IIT_Dharwad.pdf
        text: CV


format:
  html:
    favicon: "images/logo.png"
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Ariel"
    code-copy: true
    code-overflow: wrap
  
execute:
  freeze: auto

